# Generated by Django 5.0.3 on 2024-03-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "class_field",
                    models.CharField(
                        choices=[
                            ("Economy", "Economy"),
                            ("Business", "Business"),
                            ("First", "First"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "from_field",
                    models.CharField(
                        choices=[
                            ("Nairobi", "Nairobi"),
                            ("Kisumu", "Kisumu"),
                            ("Mombasa", "Mombasa"),
                            ("California", "California"),
                            ("NewYork", "New York"),
                            ("Michigan", "Michigan"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "to_field",
                    models.CharField(
                        choices=[
                            ("Nairobi", "Nairobi"),
                            ("Kisumu", "Kisumu"),
                            ("Mombasa", "Mombasa"),
                            ("California", "California"),
                            ("NewYork", "New York"),
                            ("Michigan", "Michigan"),
                        ],
                        max_length=20,
                    ),
                ),
                ("departure_date", models.DateField()),
                ("return_date", models.DateField()),
                ("adults", models.IntegerField()),
                ("children", models.IntegerField()),
                ("price", models.IntegerField()),
            ],
        ),
    ]
