# Generated by Django 5.0.3 on 2024-03-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("airline_management", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("flight_number", models.IntegerField()),
                ("origin", models.CharField(max_length=100)),
                ("destination", models.CharField(max_length=100)),
                ("departure_date", models.DateField()),
                ("departure_time", models.TimeField()),
                ("journey_hours", models.IntegerField()),
                ("intervals", models.IntegerField()),
            ],
        ),
    ]
