# Generated by Django 5.0.3 on 2024-03-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("airline_management", "0003_flight_capacity"),
    ]

    operations = [
        migrations.CreateModel(
            name="Airbus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("airbus_no", models.IntegerField(unique=True)),
                ("capacity", models.PositiveIntegerField()),
            ],
        ),
    ]
