# Generated by Django 5.0.3 on 2024-03-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("airline_management", "0004_airbus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="children",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="booking",
            name="class_field",
            field=models.CharField(
                choices=[
                    ("Economy", "Economy"),
                    ("Business", "Business"),
                    ("First", "First"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="from_field",
            field=models.CharField(
                choices=[
                    ("Nairobi", "Nairobi"),
                    ("Kisumu", "Kisumu"),
                    ("Mombasa", "Mombasa"),
                    ("California", "California"),
                    ("NewYork", "NewYork"),
                    ("Michigan", "Michigan"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="booking",
            name="return_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="to_field",
            field=models.CharField(
                choices=[
                    ("Nairobi", "Nairobi"),
                    ("Kisumu", "Kisumu"),
                    ("Mombasa", "Mombasa"),
                    ("California", "California"),
                    ("NewYork", "NewYork"),
                    ("Michigan", "Michigan"),
                ],
                max_length=20,
            ),
        ),
    ]
