# Generated by Django 5.0.3 on 2024-03-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "airline_management",
            "0005_alter_booking_children_alter_booking_class_field_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="children",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="booking",
            name="class_field",
            field=models.CharField(
                choices=[
                    ("Economy", "Economy"),
                    ("Business", "Business"),
                    ("First", "First"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="from_field",
            field=models.CharField(
                choices=[
                    ("Nairobi", "Nairobi"),
                    ("Kisumu", "Kisumu"),
                    ("Mombasa", "Mombasa"),
                    ("California", "California"),
                    ("NewYork", "New York"),
                    ("Michigan", "Michigan"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="price",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="booking",
            name="return_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="booking",
            name="to_field",
            field=models.CharField(
                choices=[
                    ("Nairobi", "Nairobi"),
                    ("Kisumu", "Kisumu"),
                    ("Mombasa", "Mombasa"),
                    ("California", "California"),
                    ("NewYork", "New York"),
                    ("Michigan", "Michigan"),
                ],
                max_length=20,
            ),
        ),
    ]
