# Generated by Django 5.0.3 on 2024-03-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "airline_management",
            "0007_alter_booking_children_alter_booking_class_field_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="class_field",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="from_field",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="price",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="to_field",
        ),
        migrations.AddField(
            model_name="booking",
            name="class_type",
            field=models.CharField(
                choices=[
                    ("Economy", "Economy"),
                    ("Business", "Business"),
                    ("First", "First"),
                ],
                default="Economy",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="destination",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="booking",
            name="origin",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="booking",
            name="adults",
            field=models.IntegerField(default=1),
        ),
    ]
