# Generated by Django 5.0.3 on 2024-03-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "airline_management",
            "0008_remove_booking_class_field_remove_booking_from_field_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origin", models.CharField(max_length=100)),
                ("destination", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
