# Generated by Django 5.0.3 on 2024-03-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("airline_management", "0009_route"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
