# Generated by Django 5.0.3 on 2024-03-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("airline_management", "0010_booking_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="email",
            field=models.EmailField(default="test@test.com", max_length=254),
            preserve_default=False,
        ),
    ]
