# Generated by Django 5.0.3 on 2024-03-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("airline_management", "0011_booking_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="payment_status",
            field=models.CharField(
                choices=[("not_paid", "Not Paid"), ("paid", "Paid")],
                default="not_paid",
                max_length=20,
            ),
        ),
    ]
