# Generated by Django 5.0.3 on 2024-03-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("airline_management", "0012_booking_payment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="seats_remaining",
            field=models.IntegerField(default="500"),
            preserve_default=False,
        ),
    ]
